# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/calculator-test',
                'doc_host': 'https://ppt34.github.io',
                'git_url': 'https://github.com/ppt34/calculator-test',
                'lib_path': 'calculator_test'},
  'syms': {'calculator_test.core': {'calculator_test.core.foo': ('core.html#foo', 'calculator_test/core.py')}}}
